### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by LucidAPs** [DevKrieger/DKBans#12]
**Version**
2.2.2

**Platform**
Paper

**Minecraft server Version**
Build#163

**Minecraft client Version**
1.14.4

**Describe the bug**
/ipban didn't work and wasn't recognized.

Error log
https://pastebin.com/9LF3WUS1

**To Reproduce**
How do we reproduce this bug?
The way tho trigger this bug.

1. Use /ban <player>
2. Use /unban <player>
3. See error

**Comment by DevKrieger** [comment]
Bug fixed in version **2.2.3**

**Information**
DKBans has a special ip ban system. A ip ban is not permanently. if a player with a banned ip tries joining, he will get automatically banned for a configured reason.

Note: Only new players will be ip banned, you can disable this in the config.

See configuration, https://github.com/DevKrieger/DKBans/wiki/Configuration-%7C-config.yml#ipban-settings
